import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  imageContainer: {
    width: "100%",
    height: 249,
    backgroundColor: "gray",
    borderRadius: 8,
    marginBottom: 32,
    marginTop: 32,
    overflow: "hidden",
  },
  postPhoto: {
    width: "100%",
    height: "100%",
  },
  inputContainer: {
    position: "relative",
    width: "100%",
  },
  input: {
    marginBottom: 16,
    backgroundColor: "#F6F6F6",
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#E5E5E5",
    color: "#212121",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    width: "100%",
    paddingRight: 40,
  },
  focused: {
    borderColor: "blue",
  },
  bthSend: {
    position: "absolute",
    right: 3,
    top: 8,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FF6C00",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  disabledButton: {
    backgroundColor: "#BDBDBD",
  },
  commentContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    width: "100%",
    marginBottom: 24,
  },
  rowReverse: {
    flexDirection: "row-reverse",
  },
  imageProfileContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#BDBDBD",
    overflow: "hidden",
  },
  profilePhoto: {
    width: "100%",
    height: "100%",
  },
  commentTextContainer: {
    flex: 1,
    backgroundColor: "#F6F6F6",
    padding: 16,
    borderRadius: 8,
  },
  commentText: {
    color: "#212121",
    fontFamily: "Roboto-Regular",
    lineHeight: 18,
    fontSize: 13,
  },
  containerEdit: {
    display: "flex",
    flexDirection: "row-reverse",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 5,
  },
  containerEditIcons: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
  },
  time: {
    color: "#BDBDBD",
    fontFamily: "Roboto-Regular",
    fontSize: 10,
    marginTop: 8,
    textAlign: "right",
  },
  noComments: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    letterSpacing: 0.3,
    textAlign: "center",
    color: "#212121",
    marginBottom: 16,
  },
});
