import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    justifyContent: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#FFF",
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    marginTop: 219,
    position: "relative",
  },
  photoContainer: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 16,
    backgroundColor: "#F6F6F6",
    overflow: "hidden",
    left: "50%",
    transform: [{ translateX: -60 }],
    top: -60,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  btnAddPhoto: {
    position: "absolute",
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FF6C00",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    left: "50%",
    transform: [{ translateX: 48 }],
    top: 20,
    backgroundColor: "#FFF",
  },
  btnAddPhotoText: {
    fontFamily: "Roboto-Thin",
    fontSize: 34,
    lineHeight: 30,
    color: "#FF6C00",
  },
  title: {
    fontFamily: "Roboto-Medium",
    fontSize: 30,
    letterSpacing: 0.3,
    textAlign: "center",
    marginTop: 92,
    marginBottom: 33,
  },
  input: {
    marginBottom: 16,
    marginLeft: 16,
    marginRight: 16,
    backgroundColor: "#F6F6F6",
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#E5E5E5",
    color: "#212121",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
  },

  error: {
    borderColor: "red",
  },
  focused: {
    borderColor: "blue",
  },
  inputContainer: {
    position: "relative",
  },
  errorText: {
    position: "absolute",
    right: 16,
    top: -16,
    color: "red",
    fontSize: 12,
  },
  btnShowPassword: {
    position: "absolute",
    right: 32,
    top: 12,
  },
  btnTextShowPassword: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "#1B4371",
  },
  btn: {
    marginTop: 27,
    width: 343,
    padding: 16,
    backgroundColor: "#FF6C00",
    borderRadius: 100,
    alignItems: "center",
    marginBottom: 16,
  },
  disabledBtn: {
    backgroundColor: "rgba(255, 108, 0, 0.5)",
  },
  btnText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "#FFF",
  },
  btnContainer: {
    alignItems: "center",
  },
  btnSignInContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  btnSignInText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "#1B4371",
  },
});
